### ISSUE TITLE
Teamspace Log in Page

### ISSUE THREAD

**Issue by Scott-CC** [creativecommons/internal#1]
When you go to the log in page and sign it, you don't go to the main page nor does the page give you a link to go anywhere else.

**Comment by mattl** [comment]
Great... and I assume your CCID is just your CC email address?

**Comment by Scott-CC** [comment]
Correct it is scott@creativecommons.org

**Comment by mattl** [comment]
Try now. Should be all set. If not, please reopen this ticket.

**Comment by Scott-CC** [comment]
all good
