### ISSUE TITLE
add peterspdx in "voiced" on IRC

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/internal#13]

**Comment by mattl** [comment]
Hey, it looks like your account isn't registered.

In IRCcloud, type /msg nickserv help register -- and you'll get some instructions on how to proceed. One that's done, assign this back to me, and I'll voice you.

**Comment by peterspdx** [comment]
That's not possible.  I was shown in "voiced" for the first few weeks post ITW in Toronto.  Will check it out, but I haven't done anything to change what I've been doing.  I suddenly simply disappeared from voiced.

**Comment by mattl** [comment]
So, we can manually voice anyone, but what you want is automatic voicing,
which requires a registered account :)

**Comment by peterspdx** [comment]
still lost as to what changed matt.  you're telling me to keep asking the help desk.  i was registered, i was automatic, but no longer.

I'll try again.  Thanks.

**Comment by mattl** [comment]
It's possible that they sent you an email with a link and you missed it.
Let me know when you're registered again and I'll add you to the access
list.
