### ISSUE TITLE
CC blog in mobile doesn't downsize pics

### ISSUE THREAD

**Issue by jayaw** [creativecommons/internal#15]
Noticed with recent two CC blog posts:
http://creativecommons.org/weblog/entry/45355
and http://creativecommons.org/weblog/entry/45228

Imgs look swell in browser on desktop, but they are oversized in mob viewing (at least Android/Chrome) and don't size down to look all nice.

Maybe related from wordpress?
https://wordpress.org/support/topic/how-to-make-site-title-fit-in-screen-for-mobile-view

There seem to be lots of pay-for-em plugins out there:
http://adaptive-images.com/

HMMM

**Comment by mattl** [comment]
Now we're using a modern Bootstrap, we should extend WordPress to add the class img-responsive on every image.

**Comment by robmyers** [comment]
I've implemented this with a regex(!) in functions.php in the theme. The images now fit on mobile. This has been deployed on cc.org and blog.cc.org.
