### ISSUE TITLE
Blog post about Rob

### ISSUE THREAD

**Issue by mattl** [creativecommons/internal#20]
# Welcome: Rob Myers!

Please welcome the latest member of the Creative Commons Team, our new
software developer Rob Myers.

Rob will be familiar to many of you as an active member of the CC
Community. In 2004, Rob organized
[the first exhibition of CC-licensed art](http://robmyers.org/2005/08/06/howto-report/).

Rob has spent the last 8 years working in the free software
community. He will be working closely with CC staff, partners, and the community on
the myriad of technical solutions that the commons needs, but working
especially closely with our education team on supporting the technical
needs of the educational output of CC.

You'll find Rob along with the rest of us in the usual places
such as our IRC channel and in GitHub, where he is `robmyers`.

Welcome Rob!

**Comment by ryanmerkley** [comment]
Good to go.
