### ISSUE TITLE
develop TM policy for fan/celebratory marks like Noun Project

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/internal#23]
Work with jayaw to develop policy for developing and hosting and making available to the public.

**Comment by janeatcc** [comment]
Do you mean like their use of CC logo on NP tshirt?

**Comment by peterspdx** [comment]
logo used on NP t-shirt is the immediate issue, but we're also thinking more broadly.  Might we want to find a home for this logo, the jx-logos, and encourage development of others that celebrate CC and encourage creative types to remix our logo but within certain parameters?  Watch for a post to the staff list kicking off this issue.

**Comment by janeatcc** [comment]
Ok. I think relatedly we should think about a TM policy for platform use of
our logos -- if we need one at all. Maybe guidelines that couch the
communications kit that is TBD. We want to encourage use of our logos on
platform integrations wherever possible.

On Mon, Apr 27, 2015 at 10:42 AM, Diane Peters <notifications@github.com>
wrote:

> logo used on NP t-shirt is the immediate issue, but we're also thinking
> more broadly. Might we want to find a home for this logo, the jx-logos, and
> encourage development of others that celebrate CC and encourage creative
> types to remix our logo but within certain parameters? Watch for a post to
> the staff list kicking off this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/internal/issues/23#issuecomment-96753375>
> .
>



-- 
Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by jayaw** [comment]
This is Mozilla's trademark policy, which includes a clear section about commercial use or reproduction of their marks:
https://www.mozilla.org/en-US/foundation/trademarks/policy/

However there's no mention of 'modified' or fan/celebratory marks, except to say that they don't allow any modification of them (!). I'm sure at one point they did have some flexibility or clarity about this. Will keep searching...

**Comment by peterspdx** [comment]
janeatcc, that should be a separate issue.  Right now, use of our logos by platforms is governed by our existing /policies page.  If there's something different we need for them specifically, then let me know.  I haven't seen any problems beyond the usual with the existing policy as it applies to platforms.  If you encounter those, then make note.  thanks.

**Comment by jayaw** [comment]
FAQ talks about this as well: https://www.mozilla.org/en-US/foundation/trademarks/faq/

IT seems I'm remembering the 'community store' that Mozilla operated for some time, but it appears it's gone now. That was a Zazzle type place where people could upload their own artwork and make it available on shirts/mugs etc.

**Comment by jayaw** [comment]
WMF's pretty exhaustive TM policy can be found here:
https://wikimediafoundation.org/wiki/Trademark_policy

relevant ss
https://wikimediafoundation.org/wiki/Trademark_policy#policy-owngoods
https://wikimediafoundation.org/wiki/Trademark_policy#policy-commercialmerch

Not surprisingly, companies like Twitter are very black and white about not allowing any commercial production or remixing/fun/etc
https://about.twitter.com/press/brand-assets
http://www.google.com/permissions/using-the-logo.html

**Comment by mattl** [comment]
If I make a book/movie/record under any CC license, sell it commercially -- I should be able to use the CC logo on my work. I believe that's the case now, and should be the case going forward.

FWIW, the Mozilla policy does mean that while Firefox is free software, you can't distribute copies of Firefox commercially, which goes against the FSF and OSI definitions.

**Comment by peterspdx** [comment]
That is the case now.  What we're talking about are speciality logos -- Jay and I agreed we shouldn't encourage people to use the NP logo in lieu of our formal double-c in a circle logo for license indicators, at least that's our initial indication.

But yes, anytime you're using a CC license, of any type, you can use the double-c in a circle logo.

**Comment by peterspdx** [comment]
Closing this issue out based on new TM policy.
