### ISSUE TITLE
Please add new conference lines to calendars

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/internal#27]
Our conference lines expired.  I got 2 new ones.  I updated the teamspace page with the info.  

Now they must be put in the calender so people book them. I know this doesn't happen often but it might happen that someone needs a conference line and it would suck if they line they booked didn't work and they had to scramble last minute.

**Comment by janeatcc** [comment]
Just checked teamspace -- the int'l one still seems to be in place? I'm
using it as a backup for a call tomorrow so just making sure that's still
the case here..

On Thu, May 21, 2015 at 1:36 PM, Mari Moreshead <notifications@github.com>
wrote:

> Our conference lines expired. I got 2 new ones. I updated the teamspace
> page with the info.
>
> Now they must be put in the calender so people book them. I know this
> doesn't happen often but it might happen that someone needs a conference
> line and it would suck if they line they booked didn't work and they had to
> scramble last minute.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/internal/issues/27>.
>



-- 
Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by mmoreshead** [comment]
Hi @janeatcc -- I have no idea.  I just know that the ones that came from "Free Conference Call" expired so I got new ones. Happy to test the line you want to use if you like!

**Comment by mmoreshead** [comment]
I should have also added the new numbers here for easy updating in calendar:

Conference line 1
Dial-in Number: (605) 562-3107
Host Access Code: 895273
Participant Access Code: 447636

Conference line 2
Dial-in Number: +1 559-546-1500
Host Access Code: 399867
Participant Access Code: 199933

**Comment by mattl** [comment]
I don't know how to do this. Do you? Happy to give you the permissions to make this happen.

**Comment by mmoreshead** [comment]
Nope, I have no idea :(

**Comment by mmoreshead** [comment]
@mattl something like https://support.google.com/a/answer/1033925 and this https://support.google.com/a/answer/1686462?hl=en 

Does that seem right?

**Comment by peterspdx** [comment]
Teamspace isn't yet updated, and yet we need to book conference lines. Can we please get this solved?

**Comment by mattl** [comment]
@peterspdx global summit and wiki stuff took priority, as we apparently never had this working properly before either. 

Anyway, you should be able to add "New conference line" number 1 and 2 to any meetings now. 

@mmoreshead wanna test it and let me know?
