### ISSUE TITLE
Wordpress login

### ISSUE THREAD

**Issue by gwenfranck** [creativecommons/internal#29]
Hi, 
I noticed that my old password for the CC blog is not working anymore - can you assign me a new one ? - thanks! not sure who I should assign this to :)

**Comment by mattl** [comment]
Hey Gwen, did you request another one from WordPress? https://creativecommons.org/wordpress/wp-login.php

**Comment by gwenfranck** [comment]
I did a couple of times, never got the mail to reset the password. - maybe I'm impatient , but usually they send that promptly, don't they?

**Comment by mattl** [comment]
Yeah, normally its pretty much instant.

I'll take a look on Monday :)
