### ISSUE TITLE
Set up a digital signature for Diane

### ISSUE THREAD

**Issue by mattl** [creativecommons/internal#3]

**Comment by peterspdx** [comment]
mattl: what do you need from me to set this up?

**Comment by mattl** [comment]
I invited you (and @sarahpearson) to Keybase.io

Once you accept the invite, let's schedule 30 mins soon to set you up.

**Comment by mattl** [comment]
Okay, @sarahpearson is all set up. The process is pretty easy on OS X. Happy to spend 30 mins setting you up whenever's good, @peterspdx
