### ISSUE TITLE
missing text is bottom notice on by-nc-sa 4.0

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/internal#30]
update notice box at bottom of legal code to include this as the second sentence, with a link to CC0.  This sentence appears in all of the other five English language 4.0 licenses:

The text of the Creative Commons public licenses is dedicated to the public domain under the CC0 Public Domain Dedication.

**Comment by mattl** [comment]
Fixed. You may need to refresh the page before you see the updated text if you've been there recently. https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
