### ISSUE TITLE
Transifex issue with Portugal

### ISSUE THREAD

**Issue by gwenfranck** [creativecommons/internal#32]
some transifex frustration from Teresa in Portugal how this happened - some help is appreciated to fix this. ... Matt, assigning it to you but if there's anyone else responsible, please let me know

"It has been a while since the last time I have logged in in Transifex. All because as you might recall - after spending hours translating and reviewing all the strings - all the strings suddenly show up as having been translated by "cc_cronuser" and not having been reviewed by anyone. I recall that at that time only 2 dozens of strings were left to review and after "the machine" had done that I couldn't figure out which ones were.
I was so upset and frustrated that only now I went back there. I am still upset though, but I've decided to mark everything as reviewed and not think about it anymore. But something should be done to avoid this. I have to know who "really" did the translation.
But first things first. There's a new (for me at least) and huge problem: when I enter the CC website, for instance this page, the website knowing my location gives me automatically a Portuguese version of it. But it's neither the "Português" version that I'm responsible for neither the "Português (BR)" version of the Brazilian team. As far as I can see the version that is showing to me is the "Português (Portugal)" version that - if I remember correctly - "cc_cronuser" created when "it" did that mess with my strings.
Can someone explain me why was this language created? This language/team whose only translator is cc-cronuser, the machine? What does this mean, what's the purpose, who is doing this, why is this still online? Can I recall how many hours I've spent doing this translation just to find out now that all this time my community has been looking at half translated pages made by a stupid machine? Half translated pages which don't even use the same terms that the other 2 versions use?!
I mean, doesn't the person responsible for the machine and ultimately for this mess knows that the "Português" version is the one from Portugal? In which countries is the "Português" version showing up then, if not in Portugal? Also, doesn't that person know that we were requested to find a common Portuguese version and that the other 2 versions of Portuguese are the result of a huge effort of mine and of the Brazilian team in finding such common version?!"

**Comment by mattl** [comment]
Can you tell which website is showing the translation?

**Comment by mattl** [comment]
Assigning this to you. Let me know, and then please assign back to me so we can investigate.

**Comment by gwenfranck** [comment]
Teresa is talking about these pages: https://creativecommons.org/licenses/?lang=pt and https://creativecommons.org/licenses/?lang=pt_BR

**Comment by RCEurope1** [comment]
@mattl I have this theory that it has something to do with languages that are spoken in several countries but are listed without a country in brackets, like "French" instead of "French (France)". For some reason, cc_cronuser might like/support to substitute the languages without country assignments with new ones that do have such a (country) to them. Question remains: Why is this done, who is doing and could we make it stop?

**Comment by RCEurope1** [comment]
... and just to add: Under my RCEurope1 account I cannot do anything about it, neither approve nor disapprove languages. The core of the problem might be at wherever is decided what language gets delivered to what IP range.

**Comment by mattl** [comment]
So none of this is done using IP addresses, but rather whatever language your browser is set to. 

@RCEurope1 -- can you get to https://www.transifex.com/organization/nkinkade/team/11342/requests/

@RCEurope1 I think you're right. Maybe something changed on the TX side of things.

Gwen, there's a third page -- https://creativecommons.org/licenses/?lang=pt_PT

Can we confirm which version Teresa is seeing, and which version they're expecting to see?

**Comment by mattl** [comment]
@gwenfranck ^^

**Comment by RCEurope1** [comment]
@mattl and @gwenfranck yes, but there it says "No join team requests. Share your projects public pages or invite people from your people's page ".

I'll try to confirm with Teresa the other question ...

**Comment by RCEurope1** [comment]
ok, with my regular TX account (jhweitzmann) I can actually change the languages, stay tuned ...

**Comment by RCEurope1** [comment]
@mattl @gwenfranck Teresa sez: "The one that is correct is this: https://creativecommons.org/licenses/?lang=pt"

can I safely disable the other ones (if I find out how that is) or will that screw something else up?

**Comment by mattl** [comment]
So, what I've done for now is copied the Portuguese translation over the top of the previous pt_PT. 

This doesn't really fix the situation, but it helps for now.
