### ISSUE TITLE
Artwork for in-kind

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/internal#33]
A nice gentleman has offered to give us a whole bunch of usb flash drives which we'll use to give out at the summit.  Ryan wants to put the CC heart logo on one side and "i love to share" on the other side.  

I'm not gifted at graphic design but Ryan said that you guys (Matt & Rob) might find this to be an easy task.  I need a png on on a transparent background of both the logo and the phrase.  

We would love to be able to give him this by the end of next week (July 3) if possible.  Can someone help me?

**Comment by mattl** [comment]
Sure. I'll do this.

**Comment by mattl** [comment]
Do we have any dimensions, etc?

**Comment by mmoreshead** [comment]
Let me check.

**Comment by mmoreshead** [comment]
Says Hector: basically the best type of logo file would be one that's larger than 600px, and has a transparent background. We work with any format, but we do like png best.

**Comment by mattl** [comment]
Okay, but surely there are some dimensions? How big is the area we have to put our logo/text?

**Comment by mmoreshead** [comment]
Small, it's a USB flash drive.  This model: https://www.usbmemorydirect.com/products/swm.htm

He'll show us before they print them.  I have to assume they'll resize as they need to, no?

**Comment by mattl** [comment]
Cool, now we have the dimensions we need :)

**Comment by mattl** [comment]
![cc-heart-flip](https://cloud.githubusercontent.com/assets/33296/8342199/66d18c2e-1a98-11e5-8d5d-79920fe853be.png)
![cc-heart](https://cloud.githubusercontent.com/assets/33296/8342198/66d1b99c-1a98-11e5-8f85-829e1da9ff47.png)

**Comment by mmoreshead** [comment]
Thank you!
