### ISSUE TITLE
Add actual conference call #s to calendar

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/internal#34]
Can't locate the original issue, and many thanks to mattl for adding the ability to reserve the two new conference lines to cal; however, without the numbers included there it forces one to have to look those up in email history.  Can we please include the dial in information in the calendar feature?

**Comment by mmoreshead** [comment]
Hey Matt, you almost got it!  It says Conference Line #1 and #2 but it doesn't actually display the dial in and conference number.  See screenshot.
![conf line sshot](https://cloud.githubusercontent.com/assets/11162279/8333495/30e547f4-1a61-11e5-8bef-d0520665afec.png)

For easy reference, the numbers are here: https://teamspace.creativecommons.org/ConferenceCall#Free_Conference_Call:

**Comment by mattl** [comment]
These are the areas of information I have available:

![screenshot from 2015-06-24 11-10-27](https://cloud.githubusercontent.com/assets/33296/8333582/a90b3a7c-1a61-11e5-8d1d-20bfdc140157.png)

It might not be possible to embed all this info in the resource.

**Comment by mmoreshead** [comment]
Maybe for resource name, you could put something like this below.  

Conf line #1 (605) 562-3107  //  Access Code: 447636 
Conf line #2 (559) 546-1500 // Access Code: 199933

**Comment by mattl** [comment]
Might take a while to propagate to your calendar, but see if that's any
better.

**Comment by mmoreshead** [comment]
Nothing yet, will check again in an hour or so.

**Comment by mattl** [comment]
Yeah, it can take a while.

**Comment by mmoreshead** [comment]
Yay, totally in there now!
