### ISSUE TITLE
Regional coordinators provide feedback and suggestions on existing ISP by 31 July 2015

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/internal#35]
Here's the document for comment:  https://docs.google.com/a/creativecommons.org/document/d/1hqTGcVWkeYe519ZdTxo_LV-QC3-K9tvWoD1dawPHew8/edit?usp=sharing

**Comment by mattl** [comment]
Can we close this out?

**Comment by peterspdx** [comment]
Will raise it once we hire a new network coordinator, so long as it's working more or less satisfactory to mattl and robmyers.
