### ISSUE TITLE
add rebecca to the wiki

### ISSUE THREAD

**Issue by mattl** [creativecommons/internal#39]

**Comment by robmyers** [comment]
@mattl wiki.cc or tspace? The former they'd just log in with CCID and I'd add them to staff.

**Comment by mattl** [comment]
Wiki.cc

**Comment by mattl** [comment]
Don't add affiliates to staff. Add them to affiliates group.

**Comment by robmyers** [comment]
Roger roger.

**Comment by robmyers** [comment]
Added. Also I wrote a script we can use to add CAS users manually and put it in maintenance/ on the wiki server.
