### ISSUE TITLE
make corporate docs accessible to Mari (and all staff) on the wiki

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/internal#40]
The docs are here: https://teamspace.creativecommons.org/CorporateDocuments

**Comment by mattl** [comment]
@mmoreshead -- you get an access denied when you click this link? https://teamspace.creativecommons.org/img_auth.php/b/b2/2._Notice_of_Articles%2C_Incorp._Application.pdf

**Comment by peterspdx** [comment]
mattl: not ALL of the corporate docs on that page should be made accessible to ALL staff.  Some of those are not for general consumption.

I'll look and let you know.  The immediate question is the organizational documents for the Canadian subsidiary.  The incorporation documentation is fine to share with all.

**Comment by mmoreshead** [comment]
Yesterday when I tried to open these, I got "Access Denied"  I double checked I was logged in and everything too - I wish I'd taken a screenshort for proof..  Now today it works and I'm a liar.  Forgive this false start.
