### ISSUE TITLE
post notice on relevant rightsstatements.org page re project leads

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/internal#41]
Indicate project leaders are DPLA and Europeana, and that it is not a project of Creative Commons

**Comment by ryanmerkley** [comment]
We're an active participant, though, aren't we? Can we make that clear without disavowing it? Something like "Creative Commons is providing advice and support" or something?

**Comment by peterspdx** [comment]
I have no problem with that. @mattl perhaps eliminate the "only" that's currently in your sentence and in insert something in the spirit Ryan suggests?

**Comment by mattl** [comment]
http://rightsstatements.org/
