### ISSUE TITLE
Please consume 568ml of fermented alcohol

### ISSUE THREAD

**Issue by mattl** [creativecommons/internal#44]
I need you to drink a beer.

:beer:

**Comment by mmoreshead** [comment]
Hoping a tall can of nut brown will be good enough for this.  I'll get it out of the fridge now.

**Comment by mattl** [comment]
Photo of the beer required.

**Comment by mmoreshead** [comment]
![2015-09-22 17 01 39](https://cloud.githubusercontent.com/assets/11162279/10031559/fe1d7288-614b-11e5-822b-afbbe97d87ed.jpg)

**Comment by mmoreshead** [comment]
Between the other most important drinks in my life.

**Comment by mattl** [comment]
Irish coffee and a mostly finished pint of gin?

**Comment by mmoreshead** [comment]
I'm so transparent.
