### ISSUE TITLE
Carolina B's last day

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/internal#47]
Carolina's last contracted day was Oct. 31.  We should cut off her access to her email and have her email do 2 things: 1) auto reply with a message about how she no longer works for CC and supply her gmail address. 2) those messages should go to Claudio for now.

What else?

**Comment by mattl** [comment]
We shouldn't send emails to Claudio, but we can offer Claudio as a contact
for CC related things in the autoresponder.

We'll offer this autoresponder for until Jan 1st, then shut off the account
completely.

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by mmoreshead** [comment]
Cool, sounds good mattl.

**Comment by claudioruiz** [comment]
I don't have problem if you put my email in the auto-respond for CC Latam related inquires.
