### ISSUE TITLE
add jane to tech mailing list

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/internal#48]
I'm dumb and can't find it. Subscribed to lists.ibiblio.org/mailman/listinfo/cc-devel - but theres tech@creativecommons dot email?

**Comment by mattl** [comment]
Go to https://creativecommons.email

---
Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by janeatcc** [comment]
woo!
