### ISSUE TITLE
cc-affiliates list down - need to get an email with final SOTC to them today for review by tomorrow

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/internal#49]
should we try to fix asap or use regional lists?

**Comment by mattl** [comment]
can you forward me anything you've got that indicates its down?

**Comment by janeatcc** [comment]
Already did.

On Mon, Nov 23, 2015 at 9:39 AM, Matt Lee <notifications@github.com> wrote:

> can you forward me anything you've got that indicates its down?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/internal/issues/49#issuecomment-159006588>
> .
>



-- 
Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015
