### ISSUE TITLE
export names of members on cc-affiliates list to doc for review, annotation and updating by staff and RCs

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/internal#50]

**Comment by mattl** [comment]
https://docs.google.com/a/creativecommons.org/spreadsheets/d/1GsQcS8xzXvaJpGyjVevBp1DA3VtpGCO-lMwTIvtpPM4/edit?usp=sharing

**Comment by peterspdx** [comment]
Can you try again, this time with the supporting information about each person that's in the box below the email address, to the extent provided? Will make the updating that much easier.

**Comment by peterspdx** [comment]
I've gone ahead and done a lot of this myself, moot.
