### ISSUE TITLE
check and fix all broken links on teamspace legal and finance pages

### ISSUE THREAD

**Issue by peterspdx** [creativecommons/internal#51]
links to ibiblio to at least our favorable determination letter (attached) appear broken. I suspect that many others are as well. See: https://teamspace.creativecommons.org/Finance#Tax_Exemptions, then click on favorable determination letter.

**Comment by mmoreshead** [comment]
I fixed this letter (uploaded new one to teamspace and fixed link).  Not sure how we should go about fixing any of the other ibibio ones -- I expect they will all die soon.

**Comment by mattl** [comment]
I made a complete dump of the ibiblio 'docs' folder and put it here https://drive.google.com/open?id=0B3V4ViR_5BJbdjNkVmxBM2RoVXM (private CC only link)
