### ISSUE TITLE
Board wiki broken

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/internal#58]
https://board.creativecommons.org/

"Sorry! This site is experiencing technical difficulties.

Try waiting a few minutes and reloading.

(Cannot access the database)"

**Comment by mattl** [comment]
Looking at this now :)

**Comment by mattl** [comment]
This was fixed a few hours ago, sorry I didn't update you.

**Comment by mmoreshead** [comment]
No prob, thanks dude.
