### ISSUE TITLE
press list auto responder email needs updating.

### ISSUE THREAD

**Issue by jayaw** [creativecommons/internal#6]
auto responder text should be updated to the fol:

Welcome to the Press List! Thank you for your interest in Creative Commons (CC). If you have any questions feel free to contact us at press@creativecommons.org.

**Comment by mattl** [comment]
there's one piece of text for all emails from Civi, so we'll need to revise it in a way that includes this text.

**Comment by mattl** [comment]
Can you draft a new auto-responder text that is generic but includes relevant info, like info@ press@ etc?

**Comment by jayaw** [comment]
How about this: 

Welcome to the mailing list, and thank you for your interest in Creative Commons (CC). If you're a member of the press, we welcome you to contact us via press@creativecommons.org. If you just have any other questions or feedback, please reach us via info@creativecommons.org. Thank you!

**Comment by peterspdx** [comment]
@kgodey I'd ask Jennie or Eric about whether this list is still used and if this task is still relevant.

**Comment by kgodey** [comment]
We no longer use Civi or press@, closing.
