### ISSUE TITLE
Press contacts in the CC Voicemail system

### ISSUE THREAD

**Issue by jayaw** [creativecommons/internal#7]
The press/media need a stable way to contact CC. 

* Presuming we can use pre-existing CC PBX setup, ideally need a dedicated phone number OR an extension that press/media can use to reach a live person and/or mailbox
* main CC voicemail intro note (so Cable!) should be updated with "Press 1 for general inquiries. For media inquiries press 2" 
* #2 should point to that dedicated mailbox
* ultimately need a phone number (and/or phone # + ext) that I can put out there publicly as the go-to way to phone CC
* Is it possible for the system to ring one or more separate phone numbers (i.e. my cell) before going right to VM?
* I know right, who uses phones anymore?

**Comment by mattl** [comment]
Nice ticket. 

Five bags of popcorn and a little Doctor Who keyring of the TARDIS to remind us of telephones.

**Comment by jayaw** [comment]
*deckerface*

**Comment by mmoreshead** [comment]
FWIW, I keep a close eye on phone messages that come into info@
